name: Check RuboCop
on:
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Run RuboCop
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rubocop
        working-directory: ./api
